//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connected.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capacity
    {
        public Capacity()
        {
            this.Item = new List<Item>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> ItemOn { get; set; }
        public Nullable<bool> ItemOff { get; set; }
        public Nullable<bool> HasAdjustables { get; set; }
        public Nullable<bool> Readable { get; set; }
    
        public virtual List<Item> Item { get; set; }
    }
}
