//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connected.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectedEntities : DbContext
    {
        public ConnectedEntities()
            : base("name=ConnectedEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Capacity> Capacity { get; set; }
        public virtual DbSet<Fridge> Fridge { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItemRegistration> ItemRegistration { get; set; }
        public virtual DbSet<ItemType> ItemType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ActivityType> ActivityType { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Adjustable> Adjustable { get; set; }
        public virtual DbSet<AdjustableType> AdjustableType { get; set; }
    }
}
