//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connected.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fridge
    {
        public int ItemId { get; set; }
        public string FridgeBrand { get; set; }
        public string FridgeMake { get; set; }
        public string FridgeModel { get; set; }
        public string ProductionDate { get; set; }
        public Nullable<bool> HasFreezer { get; set; }
        public Nullable<short> Width { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Length { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
