//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connected.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRegistration
    {
        public ItemRegistration()
        {
            this.Item = new List<Item>();
        }
    
        public int Id { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string AccessURL { get; set; }
        public Nullable<bool> isRestful { get; set; }
        public string RegistrationKey { get; set; }
    
        public virtual List<Item> Item { get; set; }
    }
}
