//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connected.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Activity = new List<Activity>();
            this.Adjustable = new List<Adjustable>();
        }
    
        public int Id { get; set; }
        public int ItemTypeId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> CapacityId { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public string OriginalId { get; set; }
    
        public virtual Capacity Capacity { get; set; }
        public virtual Fridge Fridge { get; set; }
        public virtual ItemRegistration ItemRegistration { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual List<Activity> Activity { get; set; }
        public virtual List<Adjustable> Adjustable { get; set; }
    }
}
