//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connected.DAL.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdapterTypeDIM
    {
        public AdapterTypeDIM()
        {
            this.AdapterBasic = new HashSet<AdapterBasic>();
        }
    
        public int AdapterTypeId { get; set; }
        public string AdapterType { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<AdapterBasic> AdapterBasic { get; set; }
    }
}
