//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Connected.DAL.Core;

namespace Connected.DAL.Model
{
    using System;
    using System.Collections.Generic;

    public class AdaptersViewDTO : EntityBase
    {
        public string AdapterName { get; set; }
        public int AdapterTypeId { get; set; }
        public string AdapterType { get; set; }
        public Nullable<int> MessageTypeId { get; set; }
        public string MessageType { get; set; }
        public string MessageSchema { get; set; }
        public string AdapterServiceURI { get; set; }
        public Nullable<bool> IsWCFService { get; set; }
        public string AdapterServiceOperation { get; set; }
        public Nullable<int> TimesToRetry { get; set; }
        public Nullable<int> RetryInterval { get; set; }
    }
}
