//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Connected.DAL.Core;

namespace Connected.DAL.Configuration.Model
{
    using System;
    using System.Collections.Generic;

    public class AdapterTypeDIMDTO : EntityBase
    {
        public AdapterTypeDIMDTO()
        {
            this.AdapterBasic = new HashSet<AdapterBasicDTO>();
        }
    
        //public int AdapterTypeId { get; set; }
        public string AdapterType { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<AdapterBasicDTO> AdapterBasic { get; set; }
    }
}
