//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Connected.DAL.Core;

namespace Connected.DAL.Configuration.Model
{
    using System;
    using System.Collections.Generic;

    public class AdapterBasicDTO : EntityBase
    {
        public AdapterBasicDTO() //: base("AdapterId")
        {
            this.AdapterMessageType = new HashSet<AdapterMessageType>();
            this.MessageSubscriptionDetails = new HashSet<MessageSubscriptionDetails>();
        }
    
        //public int AdapterId { get; set; }
        public string AdapterName { get; set; }
        public int AdapterTypeId { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AdapterTypeDIM AdapterTypeDIM { get; set; }
        public virtual ICollection<AdapterMessageType> AdapterMessageType { get; set; }
        public virtual ICollection<MessageSubscriptionDetails> MessageSubscriptionDetails { get; set; }
        public virtual ReceiveAdapterDetailsDTO ReceiveAdapterDetails { get; set; }
    }
}
