//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connected.Inbound.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdapterBasic
    {
        public AdapterBasic()
        {
            this.AdapterMessageType = new HashSet<AdapterMessageType>();
            this.MessageSubscriptionDetails = new HashSet<MessageSubscriptionDetails>();
        }
    
        public int AdapterId { get; set; }
        public string AdapterName { get; set; }
        public int AdapterTypeId { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AdapterTypeDIM AdapterTypeDIM { get; set; }
        public virtual ICollection<AdapterMessageType> AdapterMessageType { get; set; }
        public virtual ICollection<MessageSubscriptionDetails> MessageSubscriptionDetails { get; set; }
        public virtual ReceiveAdapterDetails ReceiveAdapterDetails { get; set; }
    }
}
