//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connected.Inbound.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectedSettingsView
    {
        public int ConnectedSettingsId { get; set; }
        public string SettingsKey { get; set; }
        public string SettingsValue { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDateTimeStamp { get; set; }
        public string CreatedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public string ModifiedUserId { get; set; }
    }
}
