//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connected.Inbound.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageType
    {
        public MessageType()
        {
            this.AdapterMessageType = new HashSet<AdapterMessageType>();
            this.MessageSubscriptionDetails = new HashSet<MessageSubscriptionDetails>();
        }
    
        public int MessageTypeId { get; set; }
        public string MessageType1 { get; set; }
        public string MessageSchema { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> UniqueIdentifierColumn { get; set; }
    
        public virtual ICollection<AdapterMessageType> AdapterMessageType { get; set; }
        public virtual ICollection<MessageSubscriptionDetails> MessageSubscriptionDetails { get; set; }
    }
}
