//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connected.Inbound.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageSubscriptionDetails
    {
        public int AdapterId { get; set; }
        public int MessageTypeId { get; set; }
        public string SubscriptionCriteria { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AdapterBasic AdapterBasic { get; set; }
        public virtual MessageType MessageType { get; set; }
    }
}
