//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendAdapter.GetData.EkinCounter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EkinCounterEntities : DbContext
    {
        public EkinCounterEntities()
            : base("name=EkinCounterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CounterHistorical> CounterHistorical { get; set; }
        public virtual DbSet<Counters> Counters { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
