//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Connected.DAL.Core;

namespace Connected.DAL.Core.Configuration.Model
{
    using System;
    using System.Collections.Generic;

    public class AdapterBasicDTO : EntityBase
    {
        public AdapterBasicDTO()
        {
            this.AdapterMessageType = new HashSet<AdapterMessageTypeDTO>();
            this.MessageSubscriptionDetails = new HashSet<MessageSubscriptionDetailsDTO>();
        }

        [Required, StringLength(60, MinimumLength = 3), Display(Name = "Adapter Name")]
        public string AdapterName { get; set; }

        [Required]
        [Display(Name = "Adapter Type")]
        public int AdapterTypeId { get; set; }

        [DataType(DataType.DateTime), Display(Name = "Registration Date")]
        [DisplayFormat(DataFormatString = "{0:G}", ApplyFormatInEditMode = true)]
        public System.DateTime RegistrationDate { get; set; }

        [DataType(DataType.DateTime), Display(Name = "Modified Date")]
        [DisplayFormat(DataFormatString = "{0:G}", ApplyFormatInEditMode = true)] //{0:dd MM yyyy hh:mm}
        public Nullable<System.DateTime> ModifiedDate { get; set; }

        [Display(Name = "Is active?")]
        public bool IsActive { get; set; }
    
        [Display(Name = "Adapter Type")]
        public virtual AdapterTypeDIMDTO AdapterTypeDIM { get; set; }
        public virtual ICollection<AdapterMessageTypeDTO> AdapterMessageType { get; set; }
        public virtual ICollection<MessageSubscriptionDetailsDTO> MessageSubscriptionDetails { get; set; }
        public virtual ReceiveAdapterDetailsDTO ReceiveAdapterDetails { get; set; }
    }
}
