//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Connected.DAL.Core;

namespace Connected.DAL.Core.Configuration.Model
{
    using System;
    using System.Collections.Generic;

    public class MessageTypeDTO : EntityBase
    {
        public MessageTypeDTO()
        {
            this.AdapterMessageType = new HashSet<AdapterMessageTypeDTO>();
            this.AuditExclusionList = new HashSet<AuditExclusionListDTO>();
            this.MessageSubscriptionDetails = new HashSet<MessageSubscriptionDetailsDTO>();
        }

        //public int MessageTypeId { get; set; }
        public string MessageType1 { get; set; }
        public string MessageSchema { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> UniqueIdentifierColumn { get; set; }
    
        public virtual ICollection<AdapterMessageTypeDTO> AdapterMessageType { get; set; }
        public virtual ICollection<AuditExclusionListDTO> AuditExclusionList { get; set; }
        public virtual ICollection<MessageSubscriptionDetailsDTO> MessageSubscriptionDetails { get; set; }
    }
}
